// flow-typed signature: aa15bf39f055b80985bc5a5cb5b8227c
// flow-typed version: <<STUB>>/eslint-config-equimper_v^2.0.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-equimper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-equimper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-equimper/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/react-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-equimper/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-equimper/index' {
  declare module.exports: $Exports<'eslint-config-equimper'>;
}
declare module 'eslint-config-equimper/index.js' {
  declare module.exports: $Exports<'eslint-config-equimper'>;
}
declare module 'eslint-config-equimper/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/best-practices'>;
}
declare module 'eslint-config-equimper/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/errors'>;
}
declare module 'eslint-config-equimper/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/es6'>;
}
declare module 'eslint-config-equimper/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/imports'>;
}
declare module 'eslint-config-equimper/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/node'>;
}
declare module 'eslint-config-equimper/rules/react-a11y.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/react-a11y'>;
}
declare module 'eslint-config-equimper/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/react'>;
}
declare module 'eslint-config-equimper/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/strict'>;
}
declare module 'eslint-config-equimper/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/style'>;
}
declare module 'eslint-config-equimper/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-equimper/rules/variables'>;
}
